federation_version: 2
subgraphs:
  users:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4001
  address:
    routing_url: http://localhost:4002
    schema:
      subgraph_url: http://localhost:4002/